# What do you want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-pvc
spec:
  storageClassName: mylocalstorage-second
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 20Gi


# How do you want to implement Volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-storage-2
spec:
  storageClassName: mylocalstorage-second
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/distvol/ELK"
    type: DirectoryOrCreate