apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  selector:
      matchLabels:
        purpose: jenkins-shared-deployment