apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: jinkins-port
      port: 8080
      nodePort: 30050
    - name: jinkins-port-1
      port: 50000
      nodePort: 30051