---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 10.13.194.192
    ports:
      - port: 1
  - addresses:
      - ip: 10.13.194.194
    ports:
      - port: 1