apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
  labels:
    purpose: jenkins-shared-deployment
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0
    readOnly: false
  persistentVolumeReclaimPolicy: Retain