---
# Source: elasticsearch/templates/client-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.32.3
    component: "client"
    heritage: Helm
    release: elasticsearch
  name: elasticsearch-client
---
# Source: elasticsearch/templates/data-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.32.3
    component: "data"
    heritage: Helm
    release: elasticsearch
  name: elasticsearch-data
---
# Source: elasticsearch/templates/master-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.32.3
    component: "master"
    heritage: Helm
    release: elasticsearch
  name: elasticsearch-master